"use client";
import { useEffect, useState } from "react";
import { SITE_MODE,audiences,compareRows,event,images,packages,signatureActivations,sponsorGoals,sponsorNeeds,stats,timeline } from "../data";
const journey=["Trước sự kiện","Check-in","Khai mạc","Trải nghiệm","Chia sẻ","Ghi nhớ"];
const SectionHead=({n,children,desc}:{n:string,children:React.ReactNode,desc?:string})=><div className="sectionHead reveal"><span>{n}</span><h2>{children}</h2>{desc&&<p>{desc}</p>}</div>;
export default function Landing(){
 const [menu,setMenu]=useState(false),[modal,setModal]=useState(false),[light,setLight]=useState<string|null>(null),[sent,setSent]=useState(false),[goal,setGoal]=useState("awareness");
 const selectedGoal=sponsorGoals.find(x=>x.id===goal)??sponsorGoals[0];
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08});document.querySelectorAll(".reveal").forEach(e=>o.observe(e));return()=>o.disconnect()},[]);
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!e.currentTarget.checkValidity()){e.currentTarget.reportValidity();return}setSent(true);e.currentTarget.reset()};
 return <main>{SITE_MODE==="internal"&&<div className="draft">DỰ THẢO · KHÔNG PHÁT HÀNH</div>}
 <header><a className="brand" href="#top"><span>VLU</span><small>VAN LANG UNIVERSITY<br/>STUDENT SUPPORT CENTER</small></a><button className="menub" onClick={()=>setMenu(!menu)} aria-label="Mở menu">☰</button><nav className={menu?"open":""}>{[["Câu chuyện","#story"],["Điểm chạm","#journey"],["Quyền lợi","#benefits"],["Gói tài trợ","#packages"],["Liên hệ","#contact"]].map(x=><a key={x[0]} href={x[1]} onClick={()=>setMenu(false)}>{x[0]}</a>)}</nav><a className="navcta" href="#contact">Đăng ký đồng hành</a></header>
 <section id="top" className="hero" style={{backgroundImage:`linear-gradient(100deg,rgba(15,17,54,.94),rgba(31,34,81,.32),rgba(215,33,52,.3)),url('${images.hero}')`}}><div className="heroContent reveal"><p className="eyebrow">HỘI KHAI GIẢNG 2026</p><h1>CONVOCATION<br/><i>DAY</i></h1><p className="eventName">TRƯỜNG ĐẠI HỌC VĂN LANG</p><p className="lead">{event.message}</p><div className="meta eventMeta"><b>{event.heroDate}</b><span>{event.sessionOne}<br/>{event.sessionTwo}</span></div><div className="actions"><a className="primary" href="#journey">Khám phá cơ hội đồng hành ↘</a><a className="ghost" href="/VLU-Hoi-Khai-Giang-2026-Proposal-Draft.txt" download>Nhận hồ sơ tài trợ</a><a className="textlink" href="#contact">Liên hệ hợp tác →</a></div></div><a className="scroll" href="#story">CUỘN ĐỂ KHÁM PHÁ ↓</a></section>
 <section id="story" className="story" style={{backgroundImage:`linear-gradient(90deg,rgba(31,34,81,.95),rgba(31,34,81,.12)),url('${images.story}')`}}><div className="reveal"><span>01 · CÂU CHUYỆN</span><h2>Nơi bạn<br/>được nhìn thấy.</h2><p>Hội Khai giảng là lời chào chính thức dành cho thế hệ K32: nơi mỗi tân sinh viên được chào đón, được kết nối và được khích lệ để bắt đầu một hành trình mang dấu ấn riêng tại Văn Lang.</p></div></section>
 <section className="section"><SectionHead n="02 · QUY MÔ">Sự kiện trong<br/>những con số</SectionHead><div className="statGrid">{stats.map(s=><article className="reveal" key={s.label}><b>{s.value}</b><h3>{s.label}</h3><small>{s.note}</small></article>)}</div></section>
 <section className="section soft"><SectionHead n="03 · CỘNG ĐỒNG">Ai sẽ có mặt?</SectionHead><div className="audienceGrid">{audiences.map((a,i)=><article className="reveal" key={a[0]}><em>0{i+1}</em><h3>{a[0]}</h3><p>{a[1]}</p></article>)}</div></section>
 <section id="journey" className="section navy"><SectionHead n="04 · BRAND JOURNEY">Một hành trình.<br/>Nhiều điểm chạm.</SectionHead><div className="journey">{journey.map((x,i)=><article className="reveal" key={x}><b>0{i+1}</b><i></i><h3>{x}</h3><p>{[["Email","Social media"],["Check-in","Backdrop"],["LED","Sân khấu"],["Gian hàng","Quà tặng"],["Minigame","Livestream"],["Nội dung hậu kỳ","Báo cáo"]][i].join(" · ")}</p></article>)}</div></section>
 <section id="benefits" className="section goalSection"><SectionHead n="05 · PARTNERSHIP DESIGN" desc="Chọn mục tiêu ưu tiên để xem cấu trúc quyền lợi phù hợp. Văn Lang không bán một danh sách logo giống nhau cho mọi thương hiệu.">Bắt đầu từ mục tiêu<br/>của doanh nghiệp</SectionHead><div className="goalTabs" role="tablist" aria-label="Mục tiêu hợp tác">{sponsorGoals.map(x=><button role="tab" aria-selected={goal===x.id} className={goal===x.id?"active":""} key={x.id} onClick={()=>setGoal(x.id)}><span>{x.label}</span><small>{x.recommend}</small></button>)}</div><div className="goalPanel" role="tabpanel"><div className="goalNarrative"><span>ĐỀ XUẤT CHO MỤC TIÊU · {selectedGoal.label.toUpperCase()}</span><h3>{selectedGoal.title}</h3><p>{selectedGoal.desc}</p><b>Gói phù hợp: {selectedGoal.recommend}</b></div><div className="goalOutcomes">{selectedGoal.outcomes.map((x,i)=><article key={x}><em>0{i+1}</em><p>{x}</p></article>)}</div></div></section>
 <section className="section soft"><SectionHead n="06 · BRAND SPACE" desc="Quảng trường Đông Sơn – địa điểm tổ chức Hội Khai giảng ngày 27/09/2026. Hình ảnh sự kiện tham chiếu từ chương trình Chào đón Tân sinh viên Khóa 31 năm 2025.">Không gian thương hiệu</SectionHead><div className="gallery">{[images.venue,images.stage,images.club].map((im,i)=><button key={im} onClick={()=>setLight(im)} className="reveal"><img src={im} loading="lazy" alt={["Toàn cảnh Quảng trường Đông Sơn tại Trường Đại học Văn Lang","Biểu diễn trên sân khấu Hội Khai giảng Văn Lang 2025","Không gian câu lạc bộ sinh viên Văn Lang 2025"][i]}/><span>{["Quảng trường Đông Sơn","Sân khấu & biểu diễn","Gian hàng & CLB"][i]}</span></button>)}</div><div className="chips">{["Sân khấu","Màn hình LED","Backdrop","Photobooth","Check-in","15–20 gian hàng","Khu khách mời","Quà tặng","Social media"].map(x=><span key={x}>{x}</span>)}</div></section>
 <section className="section navy"><SectionHead n="07 · HẠNG MỤC ƯU TIÊN" desc="Hai nhóm tiếp nhận chính: học bổng hiện kim và tài trợ hiện kim/hiện vật cho sự kiện.">Văn Lang đang tìm kiếm<br/>những nguồn lực nào?</SectionHead><div className="needGrid">{sponsorNeeds.map((x,i)=><article className="reveal" key={x[0]}><b>{String(i+1).padStart(2,"0")}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><p className="legal">Học bổng chỉ tiếp nhận bằng hiện kim, không thay thế bằng voucher. Tài trợ hiện vật được thương lượng theo từng đối tác; tỷ lệ đề xuất chuẩn tối đa 30% giá trị gói.</p></section>
 <section id="packages" className="section packageSection"><SectionHead n="08 · PARTNERSHIP LEVELS" desc="Giá trị đầu tư đã được Trưởng Ban Tổ chức xác nhận. Mỗi cấp độ được thiết kế theo mức độ sở hữu trải nghiệm và khả năng đo lường, không chỉ theo kích thước logo.">Chọn mức độ<br/>tham gia</SectionHead><div className="packageGrid">{packages.map((p,i)=><article className={`reveal packageCard tier${i+1} ${i===0?"featured":""}`} key={p.name}><div className="packageTop"><small>{i===0?"ĐỐI TÁC CHIẾN LƯỢC":"CẤP ĐỘ HỢP TÁC"}</small><em>0{i+1}</em></div><h3>{p.name}</h3><strong>{p.range}</strong><p className="packageFit">{p.fit}</p><ul>{p.rights.map((r,j)=><li key={r}><span>{String(j+1).padStart(2,"0")}</span>{r}</li>)}</ul><button onClick={()=>setModal(true)}>So sánh toàn bộ quyền lợi <b>↗</b></button></article>)}</div><div className="customPackage"><span>KHÔNG CẦN CHỌN MỘT GÓI CÓ SẴN</span><h3>Thiết kế phương án riêng theo mục tiêu</h3><p>Học bổng · Hiện vật · Hạng mục độc quyền · Branded experience · Tuyển dụng · Nội dung</p><a href="#contact">Trao đổi phương án riêng →</a></div></section>
 <section className="section activation"><SectionHead n="09 · VLU SIGNATURE OPPORTUNITIES" desc="Sáu platform trải nghiệm được phát triển từ không gian Đông Sơn, thông điệp “Nơi bạn được nhìn thấy” và nhu cầu thực tế của tân sinh viên K32.">Không chỉ hiện diện.<br/>Hãy tạo một dấu ấn.</SectionHead><div className="signatureGrid">{signatureActivations.map((x,i)=><article className="reveal" key={x.title}><div><small>{x.tag}</small><b>0{i+1}</b></div><h3>{x.title}</h3><p>{x.desc}</p><span>{x.fit}</span></article>)}</div></section>
 <section className="section soft"><SectionHead n="10 · ĐO LƯỜNG" desc="KPI truyền thông và activation sẽ được phân cấp theo từng gói, thống nhất trong phụ lục quyền lợi sau khi có kế hoạch kênh chính thức.">Giá trị được<br/>ghi nhận minh bạch</SectionHead><div className="dashboard">{[["10.000+","Quy mô người tham dự"],["7.000+","Tân sinh viên K32"],["Theo gói","Nội dung truyền thông"],["Theo booth","Lượt trải nghiệm"],["Thực tế","Sản phẩm dùng thử"],["Đối soát","Hiện kim & hiện vật"],["100%","Quyền lợi được nghiệm thu"],["30–45 ngày","Báo cáo sau sự kiện"]].map(x=><article className="reveal" key={x[1]}><b>{x[0]}</b><span>{x[1]}</span><i></i></article>)}</div></section>
 <section className="section navy"><SectionHead n="11 · QUY TRÌNH">Rõ ràng từ nhu cầu<br/>đến nghiệm thu</SectionHead><div className="fourGrid">{["Doanh nghiệp gửi nhu cầu","Hai bên thống nhất phương án","Nhà trường xem xét & phê duyệt","Ký kết, triển khai & nghiệm thu"].map((x,i)=><article className="reveal" key={x}><b>0{i+1}</b><h3>{x}</h3></article>)}</div><p className="legal">Mọi quyền lợi chỉ có hiệu lực sau khi được cấp có thẩm quyền của Nhà trường phê duyệt và thể hiện trong văn bản chính thức.</p></section>
 <section className="section"><SectionHead n="12 · LỘ TRÌNH">Từ đề xuất đến<br/>ngày hội</SectionHead><div className="eventTimeline">{timeline.map(t=><article className="reveal" key={t[0]}><b>{t[0]}</b><i></i><p>{t[1]}</p></article>)}</div></section>
 <section id="contact" className="contact navy"><div className="contactIntro reveal"><span>13 · LET&apos;S PARTNER</span><h2>Cùng Văn Lang tạo nên một khởi đầu đáng nhớ</h2><p>Đầu mối tài trợ · Nguyễn Thu Hiền · Trung tâm Hỗ trợ Sinh viên</p><div><a href="/VLU-Hoi-Khai-Giang-2026-Proposal-Draft.txt" download>Tải hồ sơ tài trợ ↓</a><a href="#form">Liên hệ Ban Tổ chức →</a></div><address>Email: {event.email}<br/>Điện thoại: {event.phone}<br/>Website: {event.website}</address><div className="qr"><div>QR</div><small>QR minh họa<br/>Kết nối form sau khi duyệt</small></div></div>
 <form id="form" onSubmit={submit} className="reveal"><h3>Đăng ký đồng hành</h3><label>Tên doanh nghiệp*<input required name="company"/></label><div className="formrow"><label>Người liên hệ*<input required name="name"/></label><label>Chức vụ<input name="role"/></label></div><div className="formrow"><label>Email*<input required type="email" name="email"/></label><label>Số điện thoại*<input required pattern="[0-9+ .-]{8,}" name="phone"/></label></div><label>Hình thức quan tâm*<select required defaultValue=""><option value="" disabled>Chọn hình thức</option><option>Tiền mặt</option><option>Sản phẩm</option><option>Dịch vụ</option><option>Hạng mục / Gói riêng</option></select></label><label>Ngân sách hoặc hạng mục dự kiến<input name="budget"/></label><label>Nội dung cần trao đổi<textarea name="message" rows={3}/></label><input className="honey" tabIndex={-1} name="website_url" aria-hidden="true"/><label className="consent"><input required type="checkbox"/> Tôi đồng ý để Ban Tổ chức sử dụng thông tin nhằm liên hệ về cơ hội hợp tác. Dữ liệu không được công khai hoặc chuyển thành quyền lợi tài trợ.</label><button className="primary" type="submit">Gửi nhu cầu hợp tác ↗</button>{sent&&<p className="success">Đã ghi nhận trên bản demo. Vui lòng kết nối Microsoft Forms, Power Automate hoặc API trước khi phát hành.</p>}</form></section>
 <footer><b>VLU · HỘI KHAI GIẢNG 2026</b><p>Ảnh: Văn Lang TV — Hội Khai giảng và Chào đón Tân sinh viên Khóa 31 năm 2025.</p><p>© 2026 · Bản dự thảo phục vụ xem xét. Không tạo thành cam kết tài trợ.</p></footer><a className="totop" href="#top" aria-label="Về đầu trang">↑</a>
 {modal&&<div className="modal" role="dialog" aria-modal="true"><div><button className="close" onClick={()=>setModal(false)}>×</button><span>MA TRẬN QUYỀN LỢI TRÌNH DUYỆT</span><h2>Bảng so sánh</h2><p>● Áp dụng · Có điều kiện: cần duyệt sản phẩm, nội dung hoặc vị trí · — Không áp dụng</p><div className="tablewrap"><table><thead><tr><th>Quyền lợi</th>{packages.map(p=><th key={p.name}>{p.name}</th>)}</tr></thead><tbody>{compareRows.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i}>{c}</td>)}</tr>)}</tbody></table></div><small>Không bán hàng tại sự kiện, không cung cấp dữ liệu sinh viên và không áp dụng quyền phát biểu trên sân khấu. Toàn bộ quyền lợi chỉ được xác lập trong văn bản được Nhà trường phê duyệt.</small></div></div>}
 {light&&<div className="modal light" onClick={()=>setLight(null)} role="dialog" aria-modal="true"><img src={light} alt="Ảnh sự kiện Văn Lang phóng lớn"/><button className="close">×</button></div>}</main>}
